class LangConfig:
    def __init__(self):
        self.lang_code = {
            "English": "en",
            "Korean": "ko",
            "Afar" : "aa",
            "Abkhazian" : "ab",
            "Afrikaans" : "af",
            "Akan" : "ak",
            "Amharic" : "am",
            "Aragonese" : "an",
            "Arabic" : "ar",
            "Assamese" : "as",
            "Azerbaijani" : "az",
            "Bashkir" : "ba",
            "Belarusian" : "be",
            "Bulgarian" : "bg",
            "Bambara" : "bm",
            "Bengali" : "bn",
            "Tibetan" : "bo",
            "Breton" : "br",
            "Bosnian" : "bs",
            "Catalan" : "ca",
            "Chechen" : "ce",
            "Corsican" : "co",
            "Czech" : "cs",
            "Chuvash" : "cv",
            "Welsh" : "cy",
            "Danish" : "da",
            "German" : "de",
            "Divehi" : "dv",
            "Dzongkha" :"dz",
            "Ewe" : "ee",
            "Greek" :"el",
            "Esperanto" : "eo",
            "Spanish" : "es",
            "Estonian" : "et",
            "Basque" : "eu",
            "Persian" : "fa",
            "Fulah":"ff",
            "Finnish" : "fi",
            "Filipino" : "fil-PH",
            "Faroese" : "fo",
            "French" : "fr",
            "Western Frisian" : "fy",
            "Irish" : "ga",
            "Scottish Gaelic":"gd",
            "Galician" : "gl",
            "Guarani" : "gn",
            "Gujarati" : "gu",
            "Manx" : "gv",
            "Hausa" : "ha",
            "Hebrew" : "he",
            "Hindi" : "hi",
            "Croatian" : "hr",
            "Haitian" : "ht",
            "Hungarian" : "hu",
            "Armenian" : "hy",
            "Interlingua" : "ia",
            "Indonesian" : "id",
            "Interlingue" : "ie",
            "Sichuan Yi" : "ii",
            "Inupiaq" : "ik",
            "Ido" : "io",
            "Icelandic" : "is",
            "Italian" : "it",
            "Inuktitut" : "iu",
            "Japanese" : "ja",
            "Javanese" : "jv",
            "Georgian" : "ka",
            "Kikuyu" : "ki",
            "Kazakh" : "kk",
            "Kalaallisut" : "kl",
            "Central Khmer" : "km",
            "Kannada" : "kn",
            "Kashmiri" : "ks",
            "Kurdish" : "ku",
            "Cornish" : "kw",
            "Kyrgyz" : "ky",
            "Latin" : "la",
            "Luxembourgish" : "lb",
            "Ganda" : "lg",
            "Lingala" : "ln",
            "Lao" : "lo",
            "Lithuanian" : "lt",
            "Luba-Katanga" : "lu",
            "Latvian" : "lv",
            "Malagasy" : "mg",
            "Maori" : "mi",
            "Macedonian" : "mk",
            "Malayalam":"ml",
            "Mongolian":"mn",
            "Marathi":"mr",
            "Malay":"ms",
            "Maltese":"mt",
            "Burmese":"my",
            "Norwegian Bokmål":"nb",
            "North Ndebele":"nd",
            "Nepali":"ne",
            "Dutch":"nl",
            "Norwegian Nynorsk":"nn",
            "Norwegian":"no",
            "South Ndebele":"nr",
            "Navajo":"nv",
            "Chichewa":"ny",
            "Occitan":"oc",
            "Oromo":"om",
            "Oriya":"or",
            "Ossetian" : "os",
            "Punjabi" : "pa",
            "Polish" : "pl",
            "Pashto" : "ps",
            "Portuguese" : "pt",
            "Quechua" : "qu",
            "Romansh" : "rm",
            "Rundi" : "rn",
            "Romanian" : "ro",
            "Russian" : "ru",
            "Kinyarwanda" : "rw",
            "Sanskrit" : "sa",
            "Sardinian" : "sc",
            "Sindhi" : "sd",
            "Northern Sami" : "se",
            "Sango" : "sg",
            "Sinhala" : "si",
            "Slovak" : "sk",
            "Slovenian" : "sl",
            "Shona" : "sn",
            "Somali" : "so",
            "Albanian" : "sq",
            "Serbian" : "sr",
            "Swati" : "ss",
            "Southern Sotho" : "st",
            "Sundanese" : "su",
            "Swedish" : "sv",
            "Swahili" : "sw",
            "Tamil" : "ta",
            "Telugu" : "te",
            "Tajik" : "tg",
            "Thai" : "th",
            "Tigrinya" : "ti",
            "Turkmen" : "tk",
            "Tagalog" : "tl",
            "Tswana" : "tn",
            "Tonga" : "to",
            "Turkish" : "tr",
            "Tsonga" : "ts",
            "Tatar" : "tt",
            "Uyghur" : "ug",
            "Ukrainian" : "uk",
            "Urdu" : "ur",
            "Uzbek" : "uz",
            "Venda" : "ve",
            "Vietnamese" : "vi",
            "Volapük" : "vo",
            "Walloon" : "wa",
            "Wolof" : "wo",
            "Xhosa" : "xh",
            "Yiddish" : "yi",
            "Yoruba" : "yo",
            "Zhuang" : "za",
            "Chinese" : "zh",
            "Zulu" : "zu",
        }
    
        # 영어 한국어
        self.lang_ko_en = {
            "영어": "English",
            "한국어": "Korean",
            "아파르어": "Afar",
            "압하스어": "Abkhazian",
            "아프리칸스어": "Afrikaans",
            "아칸어": "Akan",
            "암하라어": "Amharic",
            "아라곤어": "Aragonese",
            "아랍어": "Arabic",
            "아삼어": "Assamese",
            "아제르바이잔어": "Azerbaijani",
            "바시키르어": "Bashkir",
            "벨라루스어": "Belarusian",
            "불가리아어": "Bulgarian",
            "밤바라어": "Bambara",
            "벵골어": "Bengali",
            "티베트어": "Tibetan",
            "브르타뉴어": "Breton",
            "보스니아어": "Bosnian",
            "카탈루냐어": "Catalan",
            "체첸어": "Chechen",
            "코르시카어": "Corsican",
            "체코어": "Czech",
            "추바슈어": "Chuvash",
            "웨일스어": "Welsh",
            "덴마크어": "Danish",
            "독일어": "German",
            "디베히어": "Divehi",
            "종카어": "Dzongkha",
            "에웨어": "Ewe",
            "그리스어": "Greek",
            "에스페란토어": "Esperanto",
            "스페인어": "Spanish",
            "에스토니아어": "Estonian",
            "바스크어": "Basque",
            "페르시아어": "Persian",
            "풀라어": "Fulah",
            "핀란드어": "Finnish",
            "필리핀어": "Filipino",
            "페로어": "Faroese",
            "프랑스어": "French",
            "서프리지아어": "Western Frisian",
            "아일랜드어": "Irish",
            "스코틀랜드 게일어": "Scottish Gaelic",
            "갈리시아어": "Galician",
            "과라니어": "Guarani",
            "구자라트어": "Gujarati",
            "맹크스어": "Manx",
            "하우사어": "Hausa",
            "히브리어": "Hebrew",
            "힌디어": "Hindi",
            "크로아티아어": "Croatian",
            "아이티어": "Haitian",
            "헝가리어": "Hungarian",
            "아르메니아어": "Armenian",
            "인터링구아": "Interlingua",
            "인도네시아어": "Indonesian",
            "인터링구에": "Interlingue",
            "쓰촨 이어": "Sichuan Yi",
            "이누피아크어": "Inupiaq",
            "이도어": "Ido",
            "아이슬란드어": "Icelandic",
            "이탈리아어": "Italian",
            "이누크티투트어": "Inuktitut",
            "일본어": "Japanese",
            "자바어": "Javanese",
            "조지아어": "Georgian",
            "키쿠유어": "Kikuyu",
            "카자흐어": "Kazakh",
            "그린란드어": "Kalaallisut",
            "크메르어": "Central Khmer",
            "칸나다어": "Kannada",
            "카슈미르어": "Kashmiri",
            "쿠르드어": "Kurdish",
            "코니쉬어": "Cornish",
            "키르기스어": "Kyrgyz",
            "라틴어": "Latin",
            "룩셈부르크어": "Luxembourgish",
            "간다어": "Ganda",
            "링갈라어": "Lingala",
            "라오어": "Lao",
            "리투아니아어": "Lithuanian",
            "루바-카탕가어": "Luba-Katanga",
            "라트비아어": "Latvian",
            "말라가시어": "Malagasy",
            "마오리어": "Maori",
            "마케도니아어": "Macedonian",
            "말라얄람어": "Malayalam",
            "몽골어": "Mongolian",
            "마라티어": "Marathi",
            "말레이어": "Malay",
            "몰타어": "Maltese",
            "버마어": "Burmese",
            "노르웨이 보크몰어": "Norwegian Bokmål",
            "북부 은데벨레어": "North Ndebele",
            "네팔어": "Nepali",
            "네덜란드어": "Dutch",
            "노르웨이 뉘노르스크어": "Norwegian Nynorsk",
            "노르웨이어": "Norwegian",
            "남부 은데벨레어": "South Ndebele",
            "나바호어": "Navajo",
            "치체와어": "Chichewa",
            "오크어": "Occitan",
            "오로모어": "Oromo",
            "오리야어": "Oriya",
            "오세트어": "Ossetian",
            "펀자브어": "Punjabi",
            "폴란드어": "Polish",
            "파슈토어": "Pashto",
            "포르투갈어": "Portuguese",
            "케추아어": "Quechua",
            "로망슈어": "Romansh",
            "룬디어": "Rundi",
            "루마니아어": "Romanian",
            "러시아어": "Russian",
            "르완다어": "Kinyarwanda",
            "산스크리트어": "Sanskrit",
            "사르데냐어": "Sardinian",
            "신디어": "Sindhi",
            "북부 사미어": "Northern Sami",
            "상고어": "Sango",
            "싱할라어": "Sinhala",
            "슬로바키아어": "Slovak",
            "슬로베니아어": "Slovenian",
            "쇼나어": "Shona",
            "소말리어": "Somali",
            "알바니아어": "Albanian",
            "세르비아어": "Serbian",
            "스와티어": "Swati",
            "남부 소토어": "Southern Sotho",
            "순다어": "Sundanese",
            "스웨덴어": "Swedish",
            "스와힐리어": "Swahili",
            "타밀어": "Tamil",
            "텔루구어": "Telugu",
            "타지크어": "Tajik",
            "태국어": "Thai",
            "티그리냐어": "Tigrinya",
            "투르크멘어": "Turkmen",
            "타갈로그어": "Tagalog",
            "츠와나어": "Tswana",
            "통가어": "Tonga",
            "튀르키예어": "Turkish",
            "총가어": "Tsonga",
            "타타르어": "Tatar",
            "위구르어": "Uyghur",
            "우크라이나어": "Ukrainian",
            "우르두어": "Urdu",
            "우즈베크어": "Uzbek",
            "벤다어": "Venda",
            "베트남어": "Vietnamese",
            "볼라퓌크어": "Volapük",
            "왈룬어": "Walloon",
            "월로프어": "Wolof",
            "코사어": "Xhosa",
            "이디시어": "Yiddish",
            "요루바어": "Yoruba",
            "좡어": "Zhuang",
            "중국어": "Chinese",
            "줄루어": "Zulu",
        }

    def get_lang_code(self, lang):
        return self.lang_code[lang]
    
    def get_ko_to_en(self, lang):
        return self.lang_ko_en[lang]
